name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: define build tag
      id: vars
      run: echo "build_date=$(date +%s)" >> $GITHUB_OUTPUT
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/alpine-psimulator-build-sdk:${{steps.vars.outputs.build_date}} --tag ${{secrets.DOCKER_USER}}/alpine-psimulator-build-sdk:latest
    - name: Docker Push (latest)
      run: docker push ${{secrets.DOCKER_USER}}/alpine-psimulator-build-sdk:latest
    - name: Docker Push (tagged)
      run: docker push ${{secrets.DOCKER_USER}}/alpine-psimulator-build-sdk:${{steps.vars.outputs.build_date}}
